[package]
name = "openapi_gen"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.5.23", features = ["derive"] }
magnus = { version = "0.7.1", features = ["embed"] }

[[bin]]
name = "openapi-rust-gen"
path = "src/main.rs"

